server:
  port: 7000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: DEBUG

user-details:
  users:
    - s7445220
    - s1529639
    - s3497368
    - s1608055
    - s5871139
    - s2833776
  password: 123456
  role: USER

issuer: ${ISSUER}
